[package]
name = "os-autoinst-core"
version = "0.1.0"
edition = "2021"

[lib]
name = "os_autoinst_core"
crate-type = ["cdylib", "rlib"]

[dependencies]
image = "0.25.10"
imageproc = "0.26.1"
pyo3 = { version = "0.23.0", features = ["extension-module"] }
chrono = "0.4"
rustfft = "6.2"
hound = "3.5"

[[bin]]
name = "videoencoder"
path = "src/bin/videoencoder.rs"

[[bin]]
name = "snd2png"
path = "src/bin/snd2png.rs"
