[package]
name = "os-autoinst-core"
version = "0.1.0"
edition = "2021"

[lib]
name = "os_autoinst_core"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.23", features = ["extension-module"] }
hound = "3.5"
rustfft = "6.2"
image = "0.25"
anyhow = "1.0"
libc = "0.2"

[[bin]]
name = "videoencoder"
path = "src/bin/videoencoder.rs"

[[bin]]
name = "snd2png"
path = "src/bin/snd2png.rs"
