#!/bin/sh -e
executable=${1:-shfmt}
path=${2:-.}
if git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
    # Only check tracked files to avoid issues with local untracked directories
    files=$(git ls-files "$path" | xargs grep -l '^#!/bin/\(ba\)\?sh' 2> /dev/null ||:)
    if [ -n "$files" ]; then
        echo "$files" | xargs "$executable" -d
    fi
else
    "$executable" -d "$path"
fi
